// Code generated by protoc-gen-go.
// source: measure.proto
// DO NOT EDIT!

package distmetrics

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Measurement struct {
	ResourceId       *string     `protobuf:"bytes,1,req,name=resourceId" json:"resourceId,omitempty"`
	MetricType       *MetricType `protobuf:"varint,2,req,name=metricType,enum=distmetrics.MetricType" json:"metricType,omitempty"`
	Value            *string     `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	Timestamp        *int64      `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (this *Measurement) Reset()         { *this = Measurement{} }
func (this *Measurement) String() string { return proto.CompactTextString(this) }
func (*Measurement) ProtoMessage()       {}

func (this *Measurement) GetResourceId() string {
	if this != nil && this.ResourceId != nil {
		return *this.ResourceId
	}
	return ""
}

func (this *Measurement) GetMetricType() MetricType {
	if this != nil && this.MetricType != nil {
		return *this.MetricType
	}
	return 0
}

func (this *Measurement) GetValue() string {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return ""
}

func (this *Measurement) GetTimestamp() int64 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func init() {
}
