# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='common.proto',
  package='distmetrics',
  serialized_pb='\n\x0c\x63ommon.proto\x12\x0b\x64istmetrics*;\n\nMetricType\x12\x07\n\x03\x43pu\x10\x01\x12\x0b\n\x07MemFree\x10\x02\x12\x0b\n\x07MemUsed\x10\x03\x12\n\n\x06MemMax\x10\x04\x42\'\n%pl.project13.distmetrics.common.proto')

_METRICTYPE = descriptor.EnumDescriptor(
  name='MetricType',
  full_name='distmetrics.MetricType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='Cpu', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MemFree', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MemUsed', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MemMax', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=29,
  serialized_end=88,
)


Cpu = 1
MemFree = 2
MemUsed = 3
MemMax = 4



# @@protoc_insertion_point(module_scope)
