# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='measure.proto',
  package='distmetrics',
  serialized_pb='\n\rmeasure.proto\x12\x0b\x64istmetrics\x1a\x0c\x63ommon.proto\"p\n\x0bMeasurement\x12\x12\n\nresourceId\x18\x01 \x02(\t\x12+\n\nmetricType\x18\x02 \x02(\x0e\x32\x17.distmetrics.MetricType\x12\r\n\x05value\x18\x03 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\x03\x42\'\n%pl.project13.distmetrics.common.proto')




_MEASUREMENT = descriptor.Descriptor(
  name='Measurement',
  full_name='distmetrics.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='resourceId', full_name='distmetrics.Measurement.resourceId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='metricType', full_name='distmetrics.Measurement.metricType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='distmetrics.Measurement.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='distmetrics.Measurement.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=156,
)

_MEASUREMENT.fields_by_name['metricType'].enum_type = common_pb2._METRICTYPE
DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT

class Measurement(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEASUREMENT
  
  # @@protoc_insertion_point(class_scope:distmetrics.Measurement)

# @@protoc_insertion_point(module_scope)
